"""Add raw_scraped_text and deep dive profile fields

Revision ID: 7140e4073406
Revises: c0bb5b708d98
Create Date: 2026-09-03 15:17:41.776745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7140e4073406'
down_revision: Union[str, Sequence[str], None] = 'c0bb5b708d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('raw_scraped_text', sa.Text(), nullable=True))
    op.add_column('profile_experience', sa.Column('problem_statement', sa.Text(), nullable=True))
    op.add_column('profile_experience', sa.Column('actions_taken', sa.Text(), nullable=True))
    op.add_column('profile_experience', sa.Column('measurable_results', sa.Text(), nullable=True))
    op.add_column('profile_experience', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('profile_projects', sa.Column('problem_statement', sa.Text(), nullable=True))
    op.add_column('profile_projects', sa.Column('actions_taken', sa.Text(), nullable=True))
    op.add_column('profile_projects', sa.Column('measurable_results', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_projects', 'measurable_results')
    op.drop_column('profile_projects', 'actions_taken')
    op.drop_column('profile_projects', 'problem_statement')
    op.drop_column('profile_experience', 'tech_stack')
    op.drop_column('profile_experience', 'measurable_results')
    op.drop_column('profile_experience', 'actions_taken')
    op.drop_column('profile_experience', 'problem_statement')
    op.drop_column('jobs', 'raw_scraped_text')
    # ### end Alembic commands ###
