"""Add name and title to user profile

Revision ID: 9a850408411b
Revises: 10f93406851b
Create Date: 2026-08-30 13:56:10.149914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a850408411b'
down_revision: Union[str, Sequence[str], None] = '10f93406851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'title')
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###
