"""Add auth fields, profile_bullets table, enrich profile models

Revision ID: bfc57a1ad2a0
Revises: 9a850408411b
Create Date: 2026-08-30 14:28:43.969114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc57a1ad2a0'
down_revision: Union[str, Sequence[str], None] = '9a850408411b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_bullets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('action_verb', sa.String(), nullable=True),
    sa.Column('technologies_used', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['profile_experience.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['profile_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_bullets_id'), 'profile_bullets', ['id'], unique=False)
    op.add_column('profile_education', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profile_experience', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profile_experience', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('profile_experience', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('profile_experience', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('profile_projects', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('profile_projects', sa.Column('date_range', sa.String(), nullable=True))
    op.add_column('profile_projects', sa.Column('is_highlight', sa.Boolean(), nullable=False))
    op.add_column('profile_projects', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('profile_skills', sa.Column('category', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'portfolio_url')
    op.drop_column('user_profiles', 'github_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'phone')
    op.drop_column('user_profiles', 'headline')
    op.drop_column('profile_skills', 'category')
    op.drop_column('profile_projects', 'order')
    op.drop_column('profile_projects', 'is_highlight')
    op.drop_column('profile_projects', 'date_range')
    op.drop_column('profile_projects', 'tech_stack')
    op.drop_column('profile_experience', 'order')
    op.drop_column('profile_experience', 'end_date')
    op.drop_column('profile_experience', 'start_date')
    op.drop_column('profile_experience', 'location')
    op.drop_column('profile_education', 'location')
    op.drop_index(op.f('ix_profile_bullets_id'), table_name='profile_bullets')
    op.drop_table('profile_bullets')
    # ### end Alembic commands ###
