"""Add email fields to application

Revision ID: c0bb5b708d98
Revises: bfc57a1ad2a0
Create Date: 2026-08-30 14:30:01.619769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bb5b708d98'
down_revision: Union[str, Sequence[str], None] = 'bfc57a1ad2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('email_subject', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('email_body', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('ai_draft_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ai_draft_json')
    op.drop_column('applications', 'email_body')
    op.drop_column('applications', 'email_subject')
    # ### end Alembic commands ###
